### ISSUE TITLE
It lives! (+ one very minor observation)

### ISSUE THREAD

**Issue by Tom4c** [Saiyato/volumio-squeezelite-plugin#1] opened 2017-09-11 21:27 UTC
Just installed the Beta volumio-squeezelite-plugin on an RPi3, Volumio 2.246 and it seems to be working without any issues. It seems happy to co-exist with the Spotify plug-in too.  Brilliant.

In the plugin's settings, the "Output Device" text field is narrower than many of the options.  I assume that 99% of the time it should be left on the ALSA default.  If I end up having to specify a specific ASIO output, is there a way to read the rest of the text on the longer drop-down items?  Not a very important issue at the moment, but might become one when installing my USB DAC.

Many thanks, Tom4c.

**Comment by Saiyato** [comment] 2017-09-12 09:13
Hi Tom4c,

Unfortunately I can't control the width of the drop-down afaik. I've been thinking about what to show there, I chose to show the hardware name, mixer type and description.

On my 24" screen it showed nicely, but on my phone....

The only thing I can do is show the hardware address and mixer; and move the description to the info panel instead.

As for the default on ALSA, I'm still learning about the do's and don'ts regarding the output device... I'm leaning towards the dmix type, this way the sound application won't claim the device, making it easier to configure different applications to the soundcard. But what the implications are... I don't know yet :P

**Comment by tmsjaeger** [comment] 2017-10-25 05:23
Hi!
thanks for your programming. 
I try to use Deezer with volumio, but i found out it doesnt work so i stumbled over your plugin with squeezelite. 
however it doesnt seem to work.. when i try to configure it, it just says "no configuration available". 
in lms it says i dont have a player. 

Maybe you know what im doing wrong. 
Thanks again for your help!!
Thomas
![error 1](https://user-images.githubusercontent.com/33080995/31981729-5b143fc2-b955-11e7-8ddc-c65e8954677f.PNG)

**Comment by Saiyato** [comment] 2017-10-25 17:58
Hi Tomas,

I'm going to need to see the logging, what does the log/journal say?

**Comment by Saiyato** [comment] 2017-10-26 09:34
Problem found! It appears the old repo doesn't host the squeezelite app anymore, I've reverted to the one downloaded to this repo (ergo I have to manually update in case of new versions).

**Comment by Saiyato** [comment] 2017-10-26 10:33
Also I've moved the relevant parts of the output device to the from of the string, so it should be usable on handheld devices, I will close the issue with new commit.

**Closed as completed** 2017-10-26 10:34 UTC
Labels: enhancement

**Comment by tmsjaeger** [comment] 2017-10-27 07:36
Hi, 

thanks a lot, it all works fine now!!!
Great work!!!


Von: Rachid Groeneveld
Gesendet: Mittwoch, 25. Oktober 2017 19:58
An: Saiyato/volumio-squeezelite-plugin
Cc: tmsjaeger; Comment
Betreff: Re: [Saiyato/volumio-squeezelite-plugin] It lives! (+ one very minorobservation) (#1)

Hi Tomas,
I'm going to need to see the logging, what does the log/journal say?

**Comment by manichardtiger** [comment] 2018-12-28 08:06
Hi

I've just installed the plugin (updated 20.11.18) on volumio v. 2.406 but also get the "no configuration available" message in the plugin's settings

Also searching for "squeeze" or similar doesnt give any results

The installation appeared to complete correctly through the GUI

volumio.log :

```
2018-12-28T07:52:29.986Z - info: Downloading plugin at http://volumio.github.io/volumio-plugins/plugins/volumio/armhf/music_service/squeezelite/squeezelite.zip
2018-12-28T07:52:30.682Z - info: END DOWNLOAD: http://volumio.github.io/volumio-plugins/plugins/volumio/armhf/music_service/squeezelite/squeezelite.zip
2018-12-28T07:52:30.688Z - info: Folder /tmp/plugins removed
2018-12-28T07:52:30.861Z - info: Checking if plugin already exists
2018-12-28T07:52:30.871Z - info: Rename folder
2018-12-28T07:52:30.903Z - info: Folder /tmp/downloaded_plugin.zip removed
2018-12-28T07:52:30.915Z - info: Move to category
2018-12-28T07:52:43.512Z - info: Checking if install.sh is present
2018-12-28T07:52:43.527Z - info: Executing install.sh
2018-12-28T07:52:43.723Z - info: Installing Squeezelite and its dependencies...
2018-12-28T07:52:43.734Z - info: Downloading squeezelite...
2018-12-28T07:52:46.461Z - info: Install script completed
2018-12-28T07:52:46.469Z - info: Adding reference to registry
2018-12-28T07:52:46.480Z - info: Done installing plugin.
2018-12-28T07:52:46.501Z - info: Folder /tmp/plugins removed
2018-12-28T07:52:46.502Z - info: Folder /tmp/downloaded_plugin.zip removed
2018-12-28T07:52:46.511Z - info: Folder /data/temp removed
2018-12-28T07:52:55.637Z - info: Enabling plugin squeezelite
2018-12-28T07:52:55.642Z - info: Loading plugin "squeezelite"...
2018-12-28T07:52:55.815Z - info: Squeezelite initiated
2018-12-28T07:52:55.821Z - info: PLUGIN START: squeezelite
2018-12-28T07:52:56.378Z - info: squeezelite reloaded
2018-12-28T07:52:56.621Z - info: squeezelite started
2018-12-28T07:52:56.625Z - info: Done.
2018-12-28T07:52:58.990Z - info: CoreCommandRouter::getUIConfigOnPlugin
2018-12-28T07:52:58.993Z - info: Loaded the previous config.
2018-12-28T07:53:01.381Z - info: [{"prettyName":"Squeezelite player","name":"squeezelite","category":"music_service","version":"1.1.1","icon":"fa fa-music","enabled":true,"active":true},{"prettyName":"Youtube Playback","name":"youtube"$
2018-12-28T07:54:52.545Z - info: CoreCommandRouter::getUIConfigOnPlugin
2018-12-28T07:54:52.550Z - info: CoreCommandRouter::executeOnPlugin: appearance , getConfigParam
2018-12-28T07:54:52.681Z - info: Received Get System Version
2018-12-28T07:54:52.682Z - info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
2018-12-28T07:55:07.860Z - info: CoreCommandRouter::executeOnPlugin: alarm-clock , getAlarms
2018-12-28T07:55:13.326Z - info: CoreCommandRouter::getUIConfigOnPlugin
2018-12-28T07:55:13.402Z - info: CoreCommandRouter::executeOnPlugin: i2s_dacs , getI2sOptions
2018-12-28T07:55:13.407Z - info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
2018-12-28T07:55:13.409Z - info: CoreCommandRouter::executeOnPlugin: i2s_dacs , getI2sStatus
2018-12-28T07:55:13.451Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:55:13.456Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:55:13.457Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:55:13.459Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:55:13.460Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:55:13.462Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:55:13.463Z - info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
2018-12-28T07:56:14.761Z - info: [{"prettyName":"Squeezelite player","name":"squeezelite","category":"music_service","version":"1.1.1","icon":"fa fa-music","enabled":true,"active":true},{"prettyName":"Youtube Playback","name":"youtube"$
2018-12-28T07:56:17.432Z - info: CoreCommandRouter::getUIConfigOnPlugin
2018-12-28T07:56:17.434Z - info: Loaded the previous config.
2018-12-28T07:56:18.548Z - info: [{"prettyName":"Squeezelite player","name":"squeezelite","category":"music_service","version":"1.1.1","icon":"fa fa-music","enabled":true,"active":true},{"prettyName":"Youtube Playback","name":"youtube"$
2018-12-28T07:56:39.308Z - info: Following Redirect to: http://volumio.github.io/volumio-plugins/plugins/volumio/armhf/plugins.json
2018-12-28T07:56:54.120Z - info: CoreCommandRouter::getUIConfigOnPlugin
2018-12-28T07:56:54.122Z - info: Loaded the previous config.
2018-12-28T07:56:55.337Z - info: [{"prettyName":"Squeezelite player","name":"squeezelite","category":"music_service","version":"1.1.1","icon":"fa fa-music","enabled":true,"active":true},{"prettyName":"Youtube Playback","name":"youtube"$
2018-12-28T07:56:58.159Z - info: CoreCommandRouter::getUIConfigOnPlugin
2018-12-28T07:56:58.160Z - info: CoreCommandRouter::executeOnPlugin: appearance , getConfigParam
2018-12-28T07:56:58.231Z - info: Received Get System Version
2018-12-28T07:56:58.233Z - info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
```


Thanks!

**Comment by Saiyato** [comment] 2018-12-29 09:24
I'm not sure I can get my hands on image 2.406, does the problem persist if you re-install the plugin? It sounds like a rights issue, did you change anything to the installation other than the YouTube plugin? Anything in the file system maybe? And on what hardware are you running?

**Comment by manichardtiger** [comment] 2019-01-04 20:17
Hi

Sorry for the late reply, yes it does.

No, other than the youtube plugin nothing. Im using an orangepi zero

Thanks

**Comment by Saiyato** [comment] 2019-01-10 14:05
Does re-installing the plugin help? This is the most simple plugin, which only writes start parameters for the Squeezelite executable, the is little logic involved. The only reason I can think if is a rights problem during installation, where the UIConfig-file was not written properly. I can't reproduce this problem.
